import Head from "next/head";
import Image from "next/image";
import a from "../styles/Home.module.css";
import { Row } from "react-bootstrap";

export default function Home() {
  return (
    <div className={[a.container, a.test123].join(" ")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={a.main}>
        <h1 className="mt-5">JWT Authentication Login with NextJS/React JS</h1>
      </main>
    </div>
  );
}
